version: "2"

run:
  timeout: 5m
  tests: false

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - intrange
    - revive
    - staticcheck
    - unused
  settings:
    revive:
      rules:
        - name: use-waitgroup-go

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
